// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./utils.bs.js");

function square(x) {
  return Utils.multiply(x, x);
}

function $$double(x) {
  return Utils.add(x, x);
}

exports.square = square;
exports.$$double = $$double;
/* No side effect */
