// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

function multiply(a, b) {
  return Math.imul(a, b);
}

exports.add = add;
exports.multiply = multiply;
/* No side effect */
