// Generated by ReScript, PLEASE EDIT WITH CARE


let Link = {};

let RouterProvider = {};

let Outlet = {};

let Dom = {
  Link: Link,
  RouterProvider: RouterProvider,
  Outlet: Outlet
};

export {
  Dom,
}
/* No side effect */
