// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Math = require("./math.bs.js");
var Logger = require("./logger.bs.js");

function run() {
  var result = $$Math.square(5);
  Logger.log("Result: " + String(result));
}

exports.run = run;
/* No side effect */
