// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Math = require("./math.bs.js");
var Comp0 = require("./comp0.bs.js");
var Logger = require("./logger.bs.js");
var JsxRuntime = require("react/jsx-runtime");

function App$M(props) {
  return JsxRuntime.jsx(Comp0.make, {});
}

var M = {
  make: App$M
};

function run() {
  var result = $$Math.square(5);
  Logger.log("Result: " + String(result));
  return JsxRuntime.jsx(App$M, {
              p: 10
            });
}

exports.M = M;
exports.run = run;
/* Math Not a pure module */
