// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsxRuntime = require("react/jsx-runtime");

function Comp0(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "comp0"
                  })
            });
}

var make = Comp0;

exports.make = make;
/* react/jsx-runtime Not a pure module */
