// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./utils.bs.js");

function square(x) {
  return Utils.multiply(x, x);
}

function $$double(x) {
  return Utils.add(x, x);
}

function triple(x) {
  return Utils.multiply(x, 3);
}

var M = {
  triple: triple
};

exports.square = square;
exports.$$double = $$double;
exports.M = M;
/* No side effect */
