// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

function add(a, b) {
  return a + b | 0;
}

function multiply(a, b) {
  return Math.imul(a, b);
}

function triple(x) {
  return Math.imul(x, 3);
}

function quadruple(x) {
  return (x << 2);
}

function triple$1(x) {
  return Math.imul(x, 3);
}

function quadruple$1(x) {
  return (x << 2);
}

var U = {
  triple: triple$1,
  quadruple: quadruple$1
};

var divide = Caml_int32.div;

var whitelist = ["math"];

function is_whitelisted(module_name) {
  try {
    return Belt_Array.some(whitelist, (function (name) {
                  return name === module_name;
                }));
  }
  catch (exn){
    return false;
  }
}

exports.add = add;
exports.multiply = multiply;
exports.triple = triple;
exports.quadruple = quadruple;
exports.U = U;
exports.divide = divide;
exports.whitelist = whitelist;
exports.is_whitelisted = is_whitelisted;
/* No side effect */
