// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("rescript/lib/js/caml_int32.js");

function add(a, b) {
  return a + b | 0;
}

function multiply(a, b) {
  return Math.imul(a, b);
}

var divide = Caml_int32.div;

function sutract(a, b) {
  return a - b | 0;
}

function triple(x) {
  return Math.imul(x, 3);
}

exports.add = add;
exports.multiply = multiply;
exports.divide = divide;
exports.sutract = sutract;
exports.triple = triple;
/* No side effect */
