name: Build CLI

on:
  push:
    branches: [ main ]
    tags:
      - 'cli-v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    inputs:
      artifacts-for-extension:
        required: false
        type: boolean
        default: false

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.3.0
          dune-cache: true
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/cli-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/cli-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi
      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build project
        run: opam exec -- dune build
      - name: Create executable directory
        run: mkdir -p dist
      - name: Copy executable
        run: cp _build/default/bin/main.exe dist/rescriptdep
      - name: Set executable permissions
        run: chmod +x dist/rescriptdep
      - name: Create tar archive
        run: |
          cd dist
          tar -czf rescriptdep-darwin-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz rescriptdep
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rescriptdep-darwin-x64-${{ steps.get_version.outputs.VERSION }}
          path: dist/rescriptdep-darwin-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz
          retention-days: 7

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.3.0
          dune-cache: true
      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/cli-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/cli-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi
      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build project
        run: opam exec -- dune build
      - name: Create executable directory
        run: mkdir -p dist
      - name: Copy executable
        run: cp _build/default/bin/main.exe dist/rescriptdep
      - name: Set executable permissions
        run: chmod +x dist/rescriptdep
      - name: Create tar archive
        run: |
          cd dist
          tar -czf rescriptdep-linux-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz rescriptdep
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rescriptdep-linux-x64-${{ steps.get_version.outputs.VERSION }}
          path: dist/rescriptdep-linux-x64-${{ steps.get_version.outputs.VERSION }}.tar.gz
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.3.0
          dune-cache: true
      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/cli-v* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/cli-v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi
      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build project
        run: opam exec -- dune build
      - name: Create executable directory
        run: mkdir -p dist
      - name: Copy executable
        shell: bash
        run: cp _build/default/bin/main.exe dist/rescriptdep.exe
      - name: Create zip archive
        shell: bash
        run: |
          cd dist
          7z a rescriptdep-win32-x64-${{ steps.get_version.outputs.VERSION }}.zip rescriptdep.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: rescriptdep-win32-x64-${{ steps.get_version.outputs.VERSION }}
          path: dist/rescriptdep-win32-x64-${{ steps.get_version.outputs.VERSION }}.zip
          retention-days: 7 